apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret-sharer-app.fullname" . }}-backend-secrets
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username }}:${POSTGRESQL_PASSWORD}@{{ include "secret-sharer-app.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
  SECRET_KEY_CRYPTO: {{ .Values.backend.secrets.secretKeyCrypto | default (randAlphaNum 64) | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | default (randAlphaNum 64) | quote }}
