apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret-sharer-app.fullname" . }}-backend-secrets
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-secrets
type: Opaque
stringData:
  secret-key-crypto: {{ .Values.backend.secrets.secretKeyCrypto | quote }}
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}