apiVersion: v1
kind: Service
metadata:
  name: {{ include "secret-sharer-app.fullname" . }}-frontend
  labels:
    {{- include "secret-sharer-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort | default .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "secret-sharer-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend