apiVersion: v1
kind: Service
metadata:
    name: {{ include "secret-sharer-app.fullname" . }}-frontend
    labels:
        {{- include "secret-sharer-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
spec:
    type: {{ .Values.frontend.service.type }}
    ports:
        - port: {{ .Values.frontend.service.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        {{- include "secret-sharer-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend