apiVersion: v2
name: secret-sharer-app
description: A Helm chart for the Ephemeral Secret Sharer application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "14.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled