replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

backend:
  replicaCount: 1
  image:
    repository: sebriede66/ephemeral-secret-backend
    pullPolicy: Always
    tag: "v2.0.0"
  service:
    type: ClusterIP
    port: 3001
  frontendUrlPlaceholder: "http://TEMP_IP_PLACEHOLDER"
  secrets:
    secretKeyCrypto: "PLATZHALTER_ODER_DUMMY_BASE64_KEY"
    jwtSecret: "PLATZHALTER_ODER_DUMMY_BASE64_JWT"
  resources: {}

frontend:
  replicaCount: 1
  image:
    repository: sebriede66/ephemeral-secret-frontend
    pullPolicy: Always
    tag: "v2.0.1"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  resources: {}

postgresql:
  enabled: true
  auth:
    username: "user"
    database: "secret_sharer_db"
    existingSecret: "postgresql-secret"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "postgresql-password"
  primary:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
securityContext: {}
ingress:
  enabled: false